### PR TITLE
add missing upstream versions

### PR DESCRIPTION
**Pull request by gibsson**
Adding upstream versions of the galcore driver, hope most of them are there:
sumo-4.14.78-1.0.0 = imx-gpu-viv_6.2.4.p2.3
sumo-4.14.98-2.0.0 = imx-gpu-viv_6.2.4.p4.0
sumo-4.14.98-2.1.0 = imx-gpu-viv_6.2.4.p4.2
sumo-4.14.98-2.2.0 = imx-gpu-viv_6.2.4.p4.4
sumo-4.14.98-2.3.0 = imx-gpu-viv_6.2.4.p4.8
warrior-4.19.35-1.1.0 = imx-gpu-viv_6.4.0.p1.0

### CODE REVIEW

**Comment by gibsson** [comment]
Hi Otavio,
Seems like Github is doing some weird stuff when merging PR.
First, it didn't take the tags into account, they are missing:
https://github.com/Freescale/kernel-module-imx-gpu-viv/releases
https://github.com/boundarydevices/kernel-module-imx-gpu-viv/releases
Second it rewrote the history, the commit IDs have changed, do you know why?
Last, in the other PR, I did merge commits of the tags to follow the standard procedure of this repo, but the merges commits are gone, once again rewriting the whole history.
Let me know how we can overcome these issues.
Regards

**Comment by otavio** [comment]
It was my fault. I used the rebase merge. I fixed it now.

Please take a look.

**Comment by gibsson** [comment]
Hi Otavio,
Perfect for upstream now, thanks!
However regarding master, you used the same as BD one and I don't believe that's the best option as it doesn't include a merge for each upstream release (at some point it merge several one at once).
That's why I used my own repo which I think is cleaner:
https://github.com/gibsson/kernel-module-imx-gpu-viv/commits/master
For instance if someone wants to use release 6.2.4.p4.2 he can't find it on BD master. Since the branch has now been used by people I don't feel like force pushing but definitely I'd rather keep the Freescale version clean.
Thanks,
Gary

**Comment by otavio** [comment]
Should be good now.

**Comment by gibsson** [comment]
Perfect, thanks Otavio!

**Pull request merged**
